### ISSUE TITLE
[bug] TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [3rd-Eden/useragent#30]
Looks like your latest release introduced a new bug:

```
/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/useragent/index.js:13
  , osparserslength = osparsers.length;
                               ^
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/home/michael.heuberger/projects/binarykitchen/code/videomail/node_modules/useragent/index.js:13:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/michael.heuberger/projects/binarykitchen/code/videomail/app/lib/util/useragent.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Process finished with exit code 8
```

Any change you can fix that pretty soon? Thanks!

**Comment by klall** [comment]
We seem to run into this scenario once in a while as well when we do an npm update. 

npm update will run node_modules/useragent/bin/update.js

If I trigger an error in any of the scenarios below, I generally don't have an empty file:

`exports.update = function update(callback) {
  // Prepend local additions that are missing from the source
  fs.readFile(exports.before, 'utf8', function reading(err, before) {
    if (err) return callback(err);

    // Fetch the remote resource as that is frequently updated
    request(exports.remote, function downloading(err, res, remote) {
      if (err) return callback(err);
      if (res.statusCode !== 200) return callback(new Error('Invalid statusCode returned'));

      // Append get some local additions that are missing from the source
      fs.readFile(exports.after, 'utf8', function reading(err, after) {
        if (err) return callback(err);

        // Parse the contents
        exports.parse([ before, remote, after ], function parsing(err, results, source) {
          callback(err, results);

          if (source && !err) {
            fs.writeFile(exports.output, source, function idk(err) {
              if (err) {
                console.error('Failed to save the generated file due to reasons', err);
              }
            });
          }
        });
      });
    });
  });
};`

That is, a failed download or parse doesn't cause the issue. 

However, on occasion we do see an empty file. I am wondering if this is a concurrency issue since the nodes docs say:

"Note that it is unsafe to use fs.writeFile multiple times on the same file without waiting for the callback. For this scenario, fs.createWriteStream is strongly recommended."

Perhaps that will help - still testing further. 

Another option suggested by a colleague is that the update function could write to a temporary file and make sure there is valid content and only then rename the file. 

Thoughts?
